# Generated by Django 5.2.4 on 2025-07-02 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('energy', models.IntegerField(default=1000)),
                ('minerals', models.IntegerField(default=500)),
                ('food', models.IntegerField(default=300)),
                ('technology', models.IntegerField(default=0)),
                ('population', models.IntegerField(default=1000)),
                ('power_level', models.IntegerField(default=100)),
                ('rank', models.IntegerField(default=0)),
                ('color', models.CharField(default='#00FF00', max_length=7)),
                ('motto', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('is_open', models.BooleanField(default=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_alliances', to='game.empire')),
                ('members', models.ManyToManyField(blank=True, related_name='alliances', to='game.empire')),
            ],
        ),
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_players', models.IntegerField(default=0)),
                ('total_battles', models.IntegerField(default=0)),
                ('total_territories_conquered', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_top_empire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.empire')),
            ],
            options={
                'verbose_name_plural': 'Game Stats',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message_type', models.CharField(choices=[('diplomatic', 'Diplomatic'), ('alliance_invite', 'Alliance Invite'), ('trade_offer', 'Trade Offer'), ('declaration_of_war', 'Declaration of War'), ('peace_treaty', 'Peace Treaty')], default='diplomatic', max_length=20)),
                ('alliance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='game.alliance')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='game.empire')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='game.empire')),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('terrain_type', models.CharField(choices=[('plains', 'Plains'), ('mountains', 'Mountains'), ('desert', 'Desert'), ('forest', 'Forest'), ('water', 'Water'), ('volcanic', 'Volcanic')], default='plains', max_length=20)),
                ('resource_bonus', models.CharField(choices=[('energy', 'Energy Rich'), ('minerals', 'Mineral Rich'), ('food', 'Fertile'), ('none', 'None')], default='none', max_length=20)),
                ('defense_bonus', models.IntegerField(default=0)),
                ('occupied_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territories', to='game.empire')),
            ],
            options={
                'unique_together': {('x', 'y')},
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_type', models.CharField(choices=[('command_center', 'Command Center'), ('power_plant', 'Power Plant'), ('mine', 'Mine'), ('farm', 'Farm'), ('research_lab', 'Research Lab'), ('barracks', 'Barracks'), ('defense_system', 'Defense System'), ('spy_network', 'Spy Network'), ('factory', 'Factory')], max_length=30)),
                ('level', models.IntegerField(default=1)),
                ('built_at', models.DateTimeField(auto_now_add=True)),
                ('upgrade_started', models.DateTimeField(blank=True, null=True)),
                ('upgrade_complete', models.DateTimeField(blank=True, null=True)),
                ('empire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='game.empire')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='game.territory')),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(blank=True, choices=[('attacker_victory', 'Attacker Victory'), ('defender_victory', 'Defender Victory'), ('draw', 'Draw')], max_length=20, null=True)),
                ('battle_log', models.TextField(blank=True)),
                ('attacker_losses', models.JSONField(default=dict)),
                ('defender_losses', models.JSONField(default=dict)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacks', to='game.empire')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defenses', to='game.empire')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='game.territory')),
            ],
        ),
        migrations.CreateModel(
            name='Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('infantry', 'Infantry'), ('tanks', 'Tanks'), ('aircraft', 'Aircraft'), ('naval', 'Naval Units'), ('cyber', 'Cyber Units'), ('mechs', 'Mechs')], max_length=20)),
                ('size', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armies', to='game.empire')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armies', to='game.territory')),
            ],
        ),
        migrations.CreateModel(
            name='WorldEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('natural_disaster', 'Natural Disaster'), ('alien_invasion', 'Alien Invasion'), ('economic_crisis', 'Economic Crisis'), ('technological_breakthrough', 'Technological Breakthrough'), ('resource_discovery', 'Resource Discovery'), ('rebellion', 'Rebellion')], max_length=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('effects', models.JSONField(default=dict)),
                ('affected_territories', models.ManyToManyField(blank=True, to='game.territory')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_type', models.CharField(choices=[('energy_efficiency', 'Energy Efficiency'), ('mining_technology', 'Mining Technology'), ('agriculture', 'Agriculture'), ('military_tactics', 'Military Tactics'), ('defense_systems', 'Defense Systems'), ('espionage', 'Espionage'), ('space_travel', 'Space Travel'), ('artificial_intelligence', 'Artificial Intelligence'), ('quantum_computing', 'Quantum Computing')], max_length=30)),
                ('level', models.IntegerField(default=0)),
                ('research_started', models.DateTimeField(blank=True, null=True)),
                ('research_complete', models.DateTimeField(blank=True, null=True)),
                ('empire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='game.empire')),
            ],
            options={
                'unique_together': {('empire', 'research_type')},
            },
        ),
    ]
