# Generated by Django 5.2.4 on 2025-07-02 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empire',
            name='energy_production',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='empire',
            name='food_production',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='empire',
            name='last_resource_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='empire',
            name='mineral_production',
            field=models.IntegerField(default=5),
        ),
    ]
