# Generated by Django 5.2.4 on 2025-07-02 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_empire_energy_production_empire_food_production_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('territory', 'building_type')},
        ),
    ]
