# Generated by Django 5.2.4 on 2025-07-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_add_building_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='army',
            name='recruitment_complete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='army',
            name='recruitment_rate',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='army',
            name='recruitment_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='army',
            name='target_size',
            field=models.IntegerField(default=0),
        ),
    ]
