# Generated by Django 5.2.4 on 2025-07-02 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_add_recruitment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='armies_depart',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='armies_return',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='attacking_armies',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='battle',
            name='battle_occurs',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='defending_armies',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='battle',
            name='distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='battle',
            name='resources_captured',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='battle',
            name='source_territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_attacks', to='game.territory'),
        ),
        migrations.AddField(
            model_name='battle',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('traveling', 'Traveling'), ('fighting', 'Fighting'), ('returning', 'Returning'), ('completed', 'Completed')], default='preparing', max_length=20),
        ),
        migrations.AddField(
            model_name='battle',
            name='travel_time_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battle',
            name='defender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defenses', to='game.empire'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('diplomatic', 'Diplomatic'), ('alliance_invite', 'Alliance Invite'), ('trade_offer', 'Trade Offer'), ('declaration_of_war', 'Declaration of War'), ('peace_treaty', 'Peace Treaty'), ('attack_report', 'Attack Report')], default='diplomatic', max_length=20),
        ),
    ]
