# Generated by Django 5.2.4 on 2025-07-02 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_battle_armies_depart_battle_armies_return_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerrainMonster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster_type', models.CharField(choices=[('plains_wolves', 'Plains Wolves'), ('mountain_giants', 'Mountain Giants'), ('desert_scorpions', 'Desert Scorpions'), ('forest_treants', 'Forest Treants'), ('water_krakens', 'Water Krakens'), ('volcanic_dragons', 'Volcanic Dragons')], max_length=30)),
                ('size', models.IntegerField(default=100)),
                ('level', models.IntegerField(default=1)),
                ('respawn_time', models.DateTimeField(blank=True, null=True)),
                ('last_defeated', models.DateTimeField(blank=True, null=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monsters', to='game.territory')),
            ],
        ),
        migrations.AddField(
            model_name='battle',
            name='target_monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='game.terrainmonster'),
        ),
    ]
