# Generated by Django 5.2.4 on 2025-07-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_terrainmonster_battle_target_monster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('diplomatic', 'Diplomatic'), ('alliance_invite', 'Alliance Invite'), ('declaration_of_war', 'Declaration of War'), ('peace_treaty', 'Peace Treaty'), ('attack_report', 'Attack Report')], default='diplomatic', max_length=20),
        ),
    ]
