# Generated by Django 5.2.4 on 2025-07-05 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_message_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('territory', 'Territory'), ('battle', 'Battle'), ('building', 'Building'), ('research', 'Research'), ('alliance', 'Alliance'), ('economy', 'Economy'), ('special', 'Special')], max_length=20)),
                ('criteria_json', models.JSONField(default=dict)),
                ('reward_energy', models.IntegerField(default=0)),
                ('reward_minerals', models.IntegerField(default=0)),
                ('reward_food', models.IntegerField(default=0)),
                ('reward_technology', models.IntegerField(default=0)),
                ('is_secret', models.BooleanField(default=False)),
                ('is_repeatable', models.BooleanField(default=False)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('legendary', 'Legendary')], default='medium', max_length=10)),
                ('icon', models.CharField(default='🏆', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_type', models.CharField(choices=[('energy_efficiency', 'Energy Efficiency'), ('mining_technology', 'Mining Technology'), ('agriculture', 'Agriculture'), ('military_tactics', 'Military Tactics'), ('defense_systems', 'Defense Systems'), ('espionage', 'Espionage'), ('space_travel', 'Space Travel'), ('artificial_intelligence', 'Artificial Intelligence'), ('quantum_computing', 'Quantum Computing'), ('advanced_materials', 'Advanced Materials'), ('fusion_power', 'Fusion Power'), ('nanotechnology', 'Nanotechnology'), ('biotechnology', 'Biotechnology'), ('cybernetics', 'Cybernetics')], max_length=30)),
                ('prerequisite_research', models.CharField(choices=[('energy_efficiency', 'Energy Efficiency'), ('mining_technology', 'Mining Technology'), ('agriculture', 'Agriculture'), ('military_tactics', 'Military Tactics'), ('defense_systems', 'Defense Systems'), ('espionage', 'Espionage'), ('space_travel', 'Space Travel'), ('artificial_intelligence', 'Artificial Intelligence'), ('quantum_computing', 'Quantum Computing'), ('advanced_materials', 'Advanced Materials'), ('fusion_power', 'Fusion Power'), ('nanotechnology', 'Nanotechnology'), ('biotechnology', 'Biotechnology'), ('cybernetics', 'Cybernetics')], max_length=30)),
                ('required_level', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='alliance',
            name='defense_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alliance',
            name='non_aggression_pacts',
            field=models.ManyToManyField(blank=True, related_name='peace_with', to='game.alliance'),
        ),
        migrations.AddField(
            model_name='alliance',
            name='production_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alliance',
            name='research_bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alliance',
            name='total_battles_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alliance',
            name='total_battles_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alliance',
            name='total_power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alliance',
            name='total_territories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alliance',
            name='treasury_energy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alliance',
            name='treasury_food',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alliance',
            name='treasury_minerals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alliance',
            name='war_declarations',
            field=models.ManyToManyField(blank=True, related_name='at_war_with', to='game.alliance'),
        ),
        migrations.AddField(
            model_name='empire',
            name='is_master_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empire',
            name='master_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='army',
            name='unit_type',
            field=models.CharField(choices=[('infantry', 'Infantry'), ('tanks', 'Tanks'), ('aircraft', 'Aircraft'), ('naval', 'Naval Units'), ('cyber', 'Cyber Units'), ('mechs', 'Mechs'), ('spy', 'Spy')], max_length=20),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('global', 'Global'), ('alliance', 'Alliance'), ('private', 'Private'), ('system', 'System')], max_length=20)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_system_message', models.BooleanField(default=False)),
                ('is_announcement', models.BooleanField(default=False)),
                ('alliance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='game.alliance')),
                ('private_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_private_messages', to='game.empire')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to='game.empire')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tournament_type', models.CharField(choices=[('power_ranking', 'Power Ranking'), ('territory_conquest', 'Territory Conquest'), ('resource_gathering', 'Resource Gathering'), ('battle_royale', 'Battle Royale'), ('alliance_war', 'Alliance War')], max_length=20)),
                ('registration_start', models.DateTimeField()),
                ('registration_end', models.DateTimeField()),
                ('tournament_start', models.DateTimeField()),
                ('tournament_end', models.DateTimeField()),
                ('max_participants', models.IntegerField(default=100)),
                ('entry_fee_energy', models.IntegerField(default=0)),
                ('entry_fee_minerals', models.IntegerField(default=0)),
                ('entry_fee_food', models.IntegerField(default=0)),
                ('first_place_energy', models.IntegerField(default=0)),
                ('first_place_minerals', models.IntegerField(default=0)),
                ('first_place_food', models.IntegerField(default=0)),
                ('second_place_energy', models.IntegerField(default=0)),
                ('second_place_minerals', models.IntegerField(default=0)),
                ('second_place_food', models.IntegerField(default=0)),
                ('third_place_energy', models.IntegerField(default=0)),
                ('third_place_minerals', models.IntegerField(default=0)),
                ('third_place_food', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='tournaments', to='game.empire')),
            ],
        ),
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_energy', models.IntegerField(default=0)),
                ('offer_minerals', models.IntegerField(default=0)),
                ('offer_food', models.IntegerField(default=0)),
                ('request_energy', models.IntegerField(default=0)),
                ('request_minerals', models.IntegerField(default=0)),
                ('request_food', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trades', to='game.empire')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_trades', to='game.empire')),
            ],
        ),
        migrations.CreateModel(
            name='DiplomaticRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('neutral', 'Neutral'), ('friendly', 'Friendly'), ('allied', 'Allied'), ('hostile', 'Hostile'), ('at_war', 'At War'), ('non_aggression', 'Non-Aggression Pact'), ('trade_agreement', 'Trade Agreement')], default='neutral', max_length=20)),
                ('trust_level', models.IntegerField(default=0)),
                ('trade_modifier', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('empire_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomatic_relations_a', to='game.empire')),
                ('empire_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomatic_relations_b', to='game.empire')),
            ],
            options={
                'unique_together': {('empire_a', 'empire_b')},
            },
        ),
        migrations.CreateModel(
            name='EmpireAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.achievement')),
                ('empire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='game.empire')),
            ],
            options={
                'unique_together': {('empire', 'achievement')},
            },
        ),
    ]
