# Generated by Django 5.2.4 on 2025-07-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_achievement_researchprerequisite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empire',
            name='energy',
            field=models.IntegerField(default=5000),
        ),
        migrations.AlterField(
            model_name='empire',
            name='energy_production',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='empire',
            name='food',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='empire',
            name='food_production',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='empire',
            name='mineral_production',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='empire',
            name='minerals',
            field=models.IntegerField(default=3000),
        ),
    ]
