# Generated by Django 5.2.4 on 2025-07-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_increase_production_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='empire',
            name='energy_storage',
            field=models.IntegerField(default=6000),
        ),
        migrations.AddField(
            model_name='empire',
            name='food_storage',
            field=models.IntegerField(default=6000),
        ),
        migrations.AddField(
            model_name='empire',
            name='mineral_storage',
            field=models.IntegerField(default=6000),
        ),
    ]
