# Generated by Django 5.2.4 on 2025-07-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_add_storage_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('command_center', 'Command Center'), ('power_plant', 'Power Plant'), ('mine', 'Mine'), ('farm', 'Farm'), ('research_lab', 'Research Lab'), ('barracks', 'Barracks'), ('defense_system', 'Defense System'), ('spy_network', 'Spy Network'), ('factory', 'Factory'), ('warehouse', 'Warehouse')], max_length=30),
        ),
    ]
