# Generated by Django 5.2.4 on 2025-07-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_building_building_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='empire',
            name='energy_fraction',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='empire',
            name='food_fraction',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='empire',
            name='mineral_fraction',
            field=models.FloatField(default=0.0),
        ),
    ]
