# Generated by Django 5.2.4 on 2025-07-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_empire_energy_fraction_empire_food_fraction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='research_type',
            field=models.CharField(choices=[('warfare_tactics', 'Warfare Tactics'), ('fortification_arts', 'Fortification Arts'), ('resource_alchemy', 'Resource Alchemy'), ('agricultural_mastery', 'Agricultural Mastery'), ('mining_expertise', 'Mining Expertise'), ('royal_engineering', 'Royal Engineering'), ('diplomatic_arts', 'Diplomatic Arts')], max_length=30),
        ),
    ]
