# Generated by Django 5.2.4 on 2025-07-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_research_research_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='army',
            name='unit_type',
            field=models.CharField(choices=[('infantry', 'Infantry'), ('tanks', 'Archers'), ('aircraft', 'Spearmen'), ('naval', 'Heavy Knights'), ('cyber', 'Royal Knights'), ('spies', 'Spies')], default='infantry', max_length=20),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('command_center', 'Command Center'), ('power_plant', 'Power Plant'), ('mine', 'Mine'), ('farm', 'Farm'), ('research_lab', 'Research Lab'), ('barracks', 'Barracks'), ('defense_system', 'Defense System'), ('spy_network', 'Spy Network'), ('intelligence_hub', 'Intelligence Hub'), ('factory', 'Factory'), ('warehouse', 'Warehouse')], max_length=30),
        ),
    ]
