# Generated by Django 5.2.4 on 2025-01-05 17:15

from django.db import migrations, models


def update_unit_types_forward(apps, schema_editor):
    """Update old unit type names to new unit type names"""
    Army = apps.get_model('game', 'Army')
    
    # Mapping from old names to new names
    unit_type_mapping = {
        'tanks': 'archers',
        'aircraft': 'spearmen',
        'naval': 'heavy_knights',
        'cyber': 'royal_knights'
    }
    
    # Update existing armies
    for old_type, new_type in unit_type_mapping.items():
        Army.objects.filter(unit_type=old_type).update(unit_type=new_type)


def update_unit_types_reverse(apps, schema_editor):
    """Reverse the unit type name changes"""
    Army = apps.get_model('game', 'Army')
    
    # Mapping from new names back to old names
    reverse_mapping = {
        'archers': 'tanks',
        'spearmen': 'aircraft',
        'heavy_knights': 'naval',
        'royal_knights': 'cyber'
    }
    
    # Update existing armies back to old names
    for new_type, old_type in reverse_mapping.items():
        Army.objects.filter(unit_type=new_type).update(unit_type=old_type)


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_army_unit_type_alter_building_building_type'),
    ]

    operations = [
        migrations.RunPython(update_unit_types_forward, update_unit_types_reverse),
        migrations.AlterField(
            model_name='army',
            name='unit_type',
            field=models.CharField(choices=[('infantry', 'Infantry'), ('archers', 'Archers'), ('spearmen', 'Spearmen'), ('heavy_knights', 'Heavy Knights'), ('royal_knights', 'Royal Knights'), ('spies', 'Spies')], default='infantry', max_length=20),
        ),
    ]
