# Generated by Django 5.2.4 on 2025-07-06 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_update_unit_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(choices=[('infantry', 'Infantry'), ('archers', 'Archers'), ('spearmen', 'Spearmen'), ('heavy_knights', 'Heavy Knights'), ('royal_knights', 'Royal Knights'), ('spies', 'Spies')], default='infantry', max_length=20)),
                ('target_size', models.IntegerField(default=0)),
                ('recruitment_started', models.DateTimeField(auto_now_add=True)),
                ('recruitment_complete', models.DateTimeField(blank=True, null=True)),
                ('recruitment_rate', models.FloatField(default=1.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('empire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_batches', to='game.empire')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_batches', to='game.territory')),
            ],
        ),
    ]
