# Generated by Django 5.2.4 on 2025-07-06 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_recruitmentbatch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruitmentbatch',
            options={'ordering': ['queue_position', 'created_at']},
        ),
        migrations.AddField(
            model_name='recruitmentbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruitmentbatch',
            name='queue_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recruitmentbatch',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('active', 'Active'), ('completed', 'Completed')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='recruitmentbatch',
            name='recruitment_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
