# Generated by Django 5.2.4 on 2025-07-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_recruitmentbatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentbatch',
            name='units_added_to_army',
            field=models.IntegerField(default=0),
        ),
    ]
