# Generated by Django 5.2.4 on 2025-07-06 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_add_realtime_recruitment_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllianceInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='game.alliance')),
                ('invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='game.empire')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='game.empire')),
            ],
            options={
                'unique_together': {('alliance', 'invited')},
            },
        ),
    ]
