# Generated by Django 5.2.4 on 2025-07-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_add_alliance_invitations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='army',
            name='experience',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(choices=[('power_ranking', 'Power Ranking'), ('resource_gathering', 'Resource Gathering'), ('battle_royale', 'Battle Royale'), ('alliance_war', 'Alliance War')], max_length=20),
        ),
    ]
