# Generated by Django 5.2.4 on 2025-07-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_remove_experience_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='empire',
            name='gold',
            field=models.IntegerField(default=20),
        ),
    ]
